version: '3.1'

volumes:
  poms_mysql_data: {}


services:
  nginx-proxy:
    restart: always
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ../nginx/certs:/etc/nginx/certs
      - ../nginx/vhost:/etc/nginx/vhost.d
      - ../nginx/html:/usr/share/nginx/html

  db:
    image: library/mysql:5.7.35
    container_name: poms_mysql
    volumes:
      - poms_mysql_data:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: mysql --user=root --password=$$MYSQL_ROOT_PASSWORD -e 'SHOW DATABASES;'
      timeout: 10s
      interval: 5s
      retries: 10
    env_file:
      - .env

  django:
    container_name: pbw_liv
    build:
      context: .
      dockerfile: ./django/Dockerfile
    restart: always
    ports:
      - 8080:8080

    environment:
      VIRTUAL_HOST: testapp.projects.cch.kcl.ac.uk
      VIRTUAL_PROTO: http
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: testapp.projects.cch.kcl.ac.uk
    volumes:
      - ../testapp/config:/etc/testapp/config:ro

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1442